package no.hiof.friluftslivcompanionapp.models.enums

enum class Screen(val navBarLabelEn: String, val navBarLabelNo: String) {
    HOME ("Home", "Hjem"),
    FLORA_FAUNA ("Wildlife", "Arter"),
    FLORA_FAUNA_ADDITIONAL_INFO ("UNDEFINED", "UNDEFINED"),
    FLORA_FAUNA_ADD ("UNDEFINED", "UNDEFINED"),
    FLORA_FAUNA_SEARCH_LOCATION ("UNDEFINED", "UNDEFINED"),
    FLORA_FAUNA_SEARCH_SPECIES ("UNDEFINED", "UNDEFINED"),
    FLORA_FAUNA_SEARCH_RESULT ("UNDEFINED", "UNDEFINED"),
    PROFILE ("Profile", "Profil"),
    PROFILE_SETTINGS ("UNDEFINED", "UNDEFINED"),
    WEATHER ("Weather", "Vær"),
    WEATHER_SEARCH ("UNDEFINED", "UNDEFINED"),
    WEATHER_SEARCH_RESULT ("UNDEFINED", "UNDEFINED"),
    TRIPS ("Trips", "Turer"),
    TRIPS_ADDITIONAL_INFO ("UNDEFINED", "UNDEFINED"),
    TRIPS_ADD ("UNDEFINED", "UNDEFINED"),
    TRIPS_CREATE ("UNDEFINED", "UNDEFINED"),
    TRIPS_RECENT_ACTIVITY ("UNDEFINED", "UNDEFINED"),
    LOGIN ("UNDEFINED", "UNDEFINED")
}